# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: react-app

steps:

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonar_scanning'
        organization: 'devopsxperts-poc'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'DevOpsXperts-POC_sonar-scanning'
        cliProjectName: 'sonar-scanning'
        cliSources: 'kubernetes'


 
    - task: NodeTool@0
      inputs:
       versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        pushd src
        npm install
        npm run build
        popd
        ls
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: 'npm install and build'

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-reactapp'
        repository: 'anuj730/jpipeline_demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'react-app'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/kubernetes'
        Contents: 'deployment.yml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'react-app'
        publishLocation: 'Container'

    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    
