apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  namespace: default
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: anuj730/jpipeline_demo
        ports:
        - containerPort: 80
---        
apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: react-app
  sessionAffinity: None
  type: LoadBalancer